name: Sync JSON File

on:
  schedule:
    # 每天凌晨 2 点运行
    - cron: '0 2 * * *'
  workflow_dispatch: # 手动触发支持

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 下载 JSON 文件到 public 目录
      - name: Download JSON file
        run: |
          curl -sL https://mirrorz.org/static/json/legacy-pack.json -o ./public/legacy-pack.json

      # 检查是否有变更
      - name: Check for changes
        id: git-status
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      # 提交变更
      - name: Commit changes
        if: env.no_changes == 'false'
        run: |
          git commit -m "Update legacy-pack.json in public directory [Auto-sync]"
          git push
